<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>SASCOC Active Members Report - {{ $year }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 11px;
            color: #1c1917;
            margin: 30px;
            line-height: 1.4;
        }
        h1 {
            font-size: 20px;
            font-weight: 700;
            margin: 0 0 4px;
            color: #047857;
        }
        .subtitle {
            font-size: 12px;
            color: #57534e;
            margin: 0 0 2px;
        }
        .meta {
            font-size: 10px;
            color: #78716c;
            margin-bottom: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        thead th {
            background-color: #047857;
            color: #ffffff;
            font-size: 10px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            padding: 8px 6px;
            text-align: left;
            border-bottom: 2px solid #065f46;
        }
        tbody tr:nth-child(even) {
            background-color: #f5f5f4;
        }
        tbody td {
            padding: 6px;
            border-bottom: 1px solid #e7e5e4;
            font-size: 10px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 9px;
            color: #a8a29e;
            border-top: 1px solid #e7e5e4;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <h1>SASCOC Active Members Report &mdash; {{ $year }}</h1>
    <p class="subtitle">South African Practical Precision Rifle Federation (NPC)</p>
    <p class="meta">Generated: {{ now()->format('d F Y \a\t H:i') }} &bull; Total members: {{ $members->count() }}</p>

    <table>
        <thead>
            <tr>
                <th>SAPRF No.</th>
                <th>Full Name</th>
                <th>SA ID Number</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Province</th>
                <th>Type</th>
                <th>Start Date</th>
                <th>Expiry Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($members as $member)
                <tr>
                    <td>{{ $member->saprf_number ?? '—' }}</td>
                    <td>{{ $member->user->name ?? '—' }}</td>
                    <td>{{ $member->user->sa_id_number ?? '—' }}</td>
                    <td>{{ $member->user->email ?? '—' }}</td>
                    <td>{{ $member->user->phone ?? '—' }}</td>
                    <td>{{ $member->user->province?->name ?? '—' }}</td>
                    <td style="text-transform: capitalize;">{{ $member->membership_type ?? '—' }}</td>
                    <td>{{ $member->start_date?->format('d/m/Y') ?? '—' }}</td>
                    <td>{{ $member->expiry_date?->format('d/m/Y') ?? '—' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="9" style="text-align: center; padding: 20px; color: #a8a29e;">No active paid members found for {{ $year }}.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by SAPRF Platform &bull; saprf.co.za
    </div>
</body>
</html>
