<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>SAPRF Federation Report - {{ $year }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-size: 9px;
            color: #1c1917;
            margin: 18px;
            line-height: 1.3;
        }
        h1 {
            font-size: 16px;
            font-weight: 700;
            margin: 0 0 4px;
            color: #047857;
        }
        .subtitle { font-size: 11px; color: #57534e; margin: 0 0 2px; }
        .meta { font-size: 9px; color: #78716c; margin-bottom: 12px; }
        .summary { font-size: 10px; color: #292524; margin-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        thead th {
            background-color: #047857;
            color: #ffffff;
            font-size: 7px;
            font-weight: 600;
            padding: 4px 3px;
            text-align: left;
            border-bottom: 1px solid #065f46;
        }
        tbody tr:nth-child(even) { background-color: #f5f5f4; }
        tbody td {
            padding: 3px;
            border-bottom: 1px solid #e7e5e4;
            font-size: 7px;
            word-wrap: break-word;
        }
        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 8px;
            color: #a8a29e;
            border-top: 1px solid #e7e5e4;
            padding-top: 8px;
        }
    </style>
</head>
<body>
    <h1>SAPRF Federation Report &mdash; {{ $year }}</h1>
    <p class="subtitle">South African Precision Rifle Federation (NPC)</p>
    <p class="meta">Generated: {{ $generatedAt }} &bull; Date of issue determines junior/senior status</p>

    <p class="summary">
        Seniors: <strong>{{ $seniorCount }}</strong> &times; R{{ number_format($seniorPrice, 2) }}
        &bull; Juniors: <strong>{{ $juniorCount }}</strong> &times; R{{ number_format($juniorPrice, 2) }}
        &bull; Total due: <strong>R{{ number_format($total, 2) }}</strong>
    </p>

    <table>
        <thead>
            <tr>
                @foreach ($headers as $header)
                    <th>{{ $header }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse ($rows as $row)
                <tr>
                    @foreach ($row as $cell)
                        <td>{{ $cell }}</td>
                    @endforeach
                </tr>
            @empty
                <tr>
                    <td colspan="{{ count($headers) }}" style="text-align: center; padding: 20px; color: #a8a29e;">No qualifying members found for {{ $year }}.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by SAPRF Platform &bull; saprf.co.za
    </div>
</body>
</html>
